"""add image_file

Revision ID: 03aae6664dde
Revises: 832dcf83c05b
Create Date: 2026-10-04 23:50:26.289556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03aae6664dde'
down_revision: Union[str, Sequence[str], None] = '832dcf83c05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(), nullable=True))

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
